FROM rust:1.68.1-slim

# System dependencies for Bevy
RUN apt-get update \
    && apt-get install -y \
    pkg-config \
    libasound2-dev \
    libudev-dev \
    libwayland-dev \
    libxkbcommon-dev \
    && rm -rf /var/lib/apt/lists/*