name: CI Workflow

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_stuff:
    name: Lint, build, test
    runs-on: ubuntu-latest
    container: 
      image: gitea.okaymonkey.com/cicd/bevy-itest:latest
      credentials:
        username: henrywconklin
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check 
      - run: cargo clippy --workspace 
      - run: cargo build --workspace 
      - run: cargo test --package tessa4d
      - run: cargo test --package tessa4d-bevy --doc 
      - run: cargo test --package tessa4d-bevy --lib 
      - name: Tessa4D Bevy itest
        run: xvfb-run -s "-screen 0 1280x1024x24" cargo test --package tessa4d-bevy --test tesseract_render 
      - uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: bevy-itest-screenshots
          path: tessa4d-bevy/assets/screenshots/**/*.png 

