[package]
name = "tessa4d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.23.0", optional = true }
thiserror = "1.0.38"
godot = { git = "https://github.com/godot-rust/gdextension", rev = "7d42ebb425ada12459ca810e39f4277d6ddefd32", optional = true }


[features]
default = ["glam"]
glam = ["dep:glam"]
gdextension = ["dep:godot"]

[dev-dependencies]
rand = "0.8.5"
