[package]
name = "tessa4d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.23.0", optional = true }
bevy = { version = "0.10.1", optional = true }
thiserror = "1.0.38"

[features]
default = ["glam"]
glam = ["dep:glam"]
bevy = ["dep:bevy", "glam"]


[dev-dependencies]
proptest = "1.1.0"
rand = "0.8.5"
